export const GET_FAVORITE_LIST = 'GET_FAVORITE_LIST';
export const GET_FAVORITE_LIST_LOADING = 'GET_FAVORITE_LIST_LOADING';
export const ADD_ITEM_TO_FAVORITE_LIST = 'ADD_ITEM_TO_FAVORITE_LIST';
export const ADD_ITEM_TO_FAVORITE_LIST_LOADING = 'ADD_ITEM_TO_FAVORITE_LIST_LOADING';
export const ADD_ITEM_TO_FAVORITE_MAX_LIST = 'ADD_ITEM_TO_FAVORITE_MAX_LIST';
export const ADD_ITEM_TO_FAVORITE_LIST_ERROR = 'ADD_ITEM_TO_FAVORITE_LIST_ERROR';
export const REMOVE_ITEM_FROM_FAVORITE_LIST = 'REMOVE_ITEM_FROM_FAVORITE_LIST';
